import React from 'react';
import { Button } from '@/components/ui/button';
import { buildWhatsAppUrl } from '@/config/siteConfig';

const PricingHero = ({ hero }) => {
  const PrimaryIcon = hero.primaryCtaIcon;
  const SecondaryIcon = hero.secondaryCtaIcon;
  return <section className="px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl overflow-hidden rounded-[2.75rem] border border-purple-100 bg-[linear-gradient(135deg,_rgba(245,243,255,0.98)_0%,_rgba(255,255,255,0.97)_48%,_rgba(238,242,255,0.94)_100%)] p-8 shadow-[0_24px_80px_rgba(15,23,42,0.08)] backdrop-blur lg:p-14"><div className="grid gap-10 lg:grid-cols-[1.15fr_0.85fr] lg:items-center"><div><div className="inline-flex items-center rounded-full border border-purple-200 bg-white/80 px-4 py-2 text-xs font-semibold uppercase tracking-[0.28em] text-[#7C3AED]">InstantCare Pricing</div><h1 className="mt-6 text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">{hero.heading}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-700">{hero.subheading}</p><p className="mt-4 max-w-3xl text-base leading-8 text-slate-600">{hero.supporting}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild className="h-12 rounded-full bg-[#7C3AED] px-6 text-base font-semibold text-white hover:bg-[#6D28D9]"><a href={buildWhatsAppUrl('Hello InstantCare Team, I would like to discuss care and support for my family. Please contact me on WhatsApp and guide me on the suitable care plan and pricing.')} target="_blank" rel="noreferrer"><PrimaryIcon className="mr-2 h-4 w-4" />{hero.primaryCtaLabel}</a></Button><Button asChild variant="outline" className="h-12 rounded-full border-purple-200 bg-white px-6 text-base font-semibold text-[#7C3AED] hover:bg-purple-50"><a href="#care-plans"><SecondaryIcon className="mr-2 h-4 w-4" />{hero.secondaryCtaLabel}</a></Button></div></div><div className="rounded-[2rem] border border-slate-200/80 bg-white/90 p-6 shadow-[0_18px_50px_rgba(15,23,42,0.08)]"><p className="text-sm font-semibold uppercase tracking-[0.22em] text-slate-500">Why families connect with InstantCare</p><div className="mt-5 grid gap-3">{hero.trustPoints.map((point) => <div key={point} className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-4 text-sm font-semibold text-slate-800">{point}</div>)}</div></div></div></div></section>;
};

export default PricingHero;
