import React from 'react';
import { CircleCheckBig, CreditCard, MessageCircle, Phone, ClipboardCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { buildWhatsAppUrl, siteContact } from '@/config/siteConfig';

const careImages = [
  { src: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&fm=jpg&w=1200&q=82', alt: 'Compassionate nurse caring for an elderly patient at home' },
  { src: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&fm=jpg&w=1200&q=82', alt: 'Healthcare professional speaking warmly with a family' },
  { src: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&fm=jpg&w=1200&q=82', alt: 'Nurse checking patient health and vital signs' },
];

const guideItems = [
  ['Choosing between a caregiver and a nurse', 'The right starting point depends on what the person needs during an ordinary day. A caregiver helps with personal care, bathing, feeding, mobility, hygiene, companionship and reminders. This is often the practical foundation of patient care at home in Mumbai, especially when a family member cannot safely manage daily routines alone. A professional nurse is appropriate when the requirement includes clinical observation or nursing procedures within the professional’s scope. Some families need both at different times: a caregiver for continuity and scheduled nurse visits for clinical tasks. InstantCare clarifies these roles before confirming a plan so the family understands who will do what. This distinction protects the patient, avoids unrealistic expectations and makes the starting price easier to interpret.'],
  ['When 12-hour or 24-hour support makes sense', 'Twelve-hour patient care can suit a person who needs sustained help during the day or night but has reliable family support for the remaining hours. It may cover the busiest part of the routine, such as meals, hygiene, mobility and medicine reminders. Twenty-four-hour patient care in Mumbai is considered when the person should not be left without support, when family cannot cover the second half of the day, or when care routines continue overnight. A 24-hour arrangement still needs a sensible discussion about rest, duties and shift structure; it should not be treated as one person working without limits. Professional 24-hour nursing is a separate customised plan because clinical skill, handovers and patient complexity affect staffing. The care team explains the practical arrangement before service begins.'],
  ['Planning care after a hospital discharge', 'The first days at home can feel unexpectedly demanding. Discharge instructions may involve medicines, follow-up appointments, diagnostics, wound support, mobility precautions and changes to the home routine. Post-hospital care at home in Mumbai works best when responsibilities are made clear before the patient arrives. InstantCare can help coordinate the agreed caregiver or nursing support, doctor follow-ups, diagnostic schedules and physiotherapy where required. The treating team’s advice remains the clinical reference; home support should reinforce that plan rather than invent a new one. Families should share relevant discharge guidance privately during assessment, not through the short public enquiry form. A coordinated transition reduces missed tasks and gives relatives a clearer view of what is happening each day.'],
  ['Supporting a bedridden person with dignity', 'Bedridden patient care at home in Mumbai is about more than completing a checklist. The person may need help with hygiene, feeding, comfort, mobility, positioning and communication while still being treated with privacy and respect. The family may also need nursing coordination, doctor visits, equipment planning or physiotherapy coordination depending on medical advice. InstantCare first separates daily caregiver responsibilities from professional clinical work, then helps organise the agreed support. Needs can change during recovery, so communication with the family matters as much as the initial schedule. No website price can responsibly predict every bedridden care plan. A conversation about the home environment, patient condition, timing and available family support is necessary before staff and final pricing are confirmed.'],
  ['Elder care that preserves independence', 'Elder care services in Mumbai do not always begin with intensive medical needs. A parent may be mostly independent but need companionship, safer mobility, reminders, appointment support or someone dependable during hospital visits. Good elderly care at home should strengthen the person’s routine without taking away choices they can still make. InstantCare can build support around daily assistance, check-ups, medicine reminders, family updates and longer-term coordination. If professional nursing becomes necessary, it can be added as a distinct responsibility. Families arranging a caregiver for elderly parents in Mumbai should discuss habits, preferred communication and boundaries, not only tasks. Respectful consistency helps the parent feel supported rather than managed, while relatives gain practical visibility into important changes.'],
  ['Cancer care support without unsupported promises', 'Cancer care support at home in Mumbai should complement the treating oncology team, not replace it. InstantCare focuses on practical coordination and compassionate support: treatment appointments, chemotherapy schedules, diagnostics, hospital communication, nurse visits, post-treatment routines and family updates. The service does not claim to treat cancer or guarantee an outcome. A patient may need different kinds of help at different stages, and those requirements can change quickly. Keeping schedules, transport, visits and communication organised can reduce the logistical pressure on the patient and family. Where physiotherapy or nursing is appropriate, the team can help coordinate qualified support based on the agreed plan. Final scope and price are confirmed only after the current requirement is understood.'],
  ['How NRI parent care works across time zones', 'NRI parent care in Mumbai gives families abroad a reliable point of coordination on the ground. Distance often makes simple tasks difficult: confirming whether a parent attended an appointment, finding someone for a hospital visit, arranging home support or understanding which staff member to call. An NRI elderly care plan can bring caregiver coordination, nurse visits, health checks, appointments, diagnostics, hospital support and family communication into one operating rhythm. InstantCare agrees how and when updates should be shared so relatives receive useful context without trying to supervise every minute from another country. NRI Platinum is intended for broader, continuing requirements and starts from the price shown on this page. A smaller custom plan may be more suitable when the family needs fewer services.'],
  ['When complete home and patient management helps', 'Some situations extend beyond home nursing. A parent may need a caregiver, a driver for appointments, a cook who follows the household routine, housekeeping support, diagnostics, doctor visits and regular family updates. Managing each person separately creates repeated calls and unclear accountability. InstantCare 360° offers complete home care management through one coordinated team, with the exact responsibilities documented for the family. Home staff remain distinct from healthcare professionals, but their schedules can be organised around the same household reality. This approach can be especially useful for NRIs, busy professionals and families managing long recovery periods. The plan is customised because the useful combination of patient care, home staff management and healthcare coordination is different in every home.'],
];

const PricingStorySections = () => {
  const generalMessage = 'Hello InstantCare Team, I would like to discuss a suitable care plan for my family. Please contact me on WhatsApp regarding options, availability and final pricing.';
  return <>
    <section className="px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.28em] text-[#7C3AED]">Human Care, Clearly Organised</p><h2 className="mt-3 text-3xl font-bold text-slate-950 sm:text-4xl">Behind every care plan is a real person, a real family and a real responsibility.</h2><p className="mt-5 text-base leading-8 text-slate-600">We know that trust cannot be created by a pricing card alone. It comes from communication, consistency, respectful behaviour and doing what was agreed.</p><p className="mt-4 text-base leading-8 text-slate-600">Whether you need a nurse at home in Mumbai, a caregiver for elderly parents or post-hospital care at home, the first step is a practical conversation. Our team listens to the situation, clarifies what kind of professional is suitable and explains what happens next.</p></div><div className="grid grid-cols-2 gap-3 sm:gap-4">{careImages.map((image, index) => <img key={image.src} src={image.src} alt={image.alt} loading="lazy" className={`h-52 w-full rounded-2xl object-cover sm:h-64 ${index === 0 ? 'col-span-2' : ''}`} />)}</div></div></div></section>

    <section className="border-y border-purple-100 bg-purple-50/70 px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.28em] text-[#7C3AED]">How Pricing Works</p><h2 className="mt-3 text-3xl font-bold text-slate-950 sm:text-4xl">A starting price for clarity, followed by a plan built around the real requirement</h2><p className="mt-5 leading-8 text-slate-600">Home healthcare is not a one-size-fits-all purchase. A scheduled nurse visit, 12-hour patient care, 24-hour nursing and complete family care management involve different skills, schedules and levels of coordination. The prices on this page help you understand the likely starting point without asking you to calculate the final bill.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[['1. Share the basics', 'Tell us the care category, location and how we can reach you. Detailed medical history is not required in the enquiry form.'], ['2. Speak with the care team', 'We clarify whether the family needs caregiver support, professional nursing, visits, recovery coordination or a broader care plan.'], ['3. Receive confirmed scope', 'The team confirms availability, responsibilities and final pricing before service begins. An enquiry never auto-confirms a booking.']].map(([title, body]) => <article key={title} className="border-l-4 border-[#7C3AED] bg-white p-6 shadow-sm"><h3 className="text-xl font-bold text-slate-950">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{body}</p></article>)}</div></div></section>

    <section className="px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><div className="max-w-4xl"><p className="text-sm font-semibold uppercase tracking-[0.28em] text-[#7C3AED]">A Practical Guide for Families</p><h2 className="mt-3 text-3xl font-bold text-slate-950 sm:text-4xl">Understanding home healthcare before you choose a plan</h2><p className="mt-5 text-base leading-8 text-slate-600">Most families arrive here because something has changed: a parent is less independent, a patient is coming home from hospital, or relatives abroad can no longer coordinate every appointment by phone. These explanations are designed to help you understand the choices without turning a personal situation into a complicated calculator.</p><p className="mt-4 text-base leading-8 text-slate-600">After the first WhatsApp message, the care team reviews the location and the kind of support you selected. A team member then speaks with you to separate immediate needs from longer-term coordination, explain which role may be suitable and check realistic availability. You can ask questions before accepting anything, and an enquiry does not create a booking or payment. When the requirement is clear, the team confirms the proposed responsibilities, schedule and final price. Families with more complex situations may need a deeper private assessment before staffing is recommended. This sequence gives you a practical answer to what InstantCare can do, what it may cost and what information is still needed, without asking you to share sensitive medical details in a public web form.</p></div><div className="mt-12 grid gap-x-12 gap-y-10 md:grid-cols-2">{guideItems.map(([title, body]) => <article key={title} className="border-t border-purple-200 pt-6"><h3 className="text-2xl font-bold text-slate-950">{title}</h3><p className="mt-4 leading-8 text-slate-600">{body}</p></article>)}</div></div></section>

    <section className="px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl grid gap-8 lg:grid-cols-[1fr_0.8fr] lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.28em] text-[#7C3AED]">Secure & Flexible Payment Options</p><h2 className="mt-3 text-3xl font-bold text-slate-950 sm:text-4xl">Confirm the care plan before arranging payment</h2><p className="mt-5 leading-8 text-slate-600">Online checkout is not currently enabled for pricing-page enquiries. Because care scope and availability must be confirmed first, the team will explain the applicable payment process after discussing your requirement. No booking or payment is created when you submit the enquiry form.</p><div className="mt-6 flex flex-wrap gap-3 text-sm font-semibold text-slate-700"><span className="rounded-full border border-slate-200 bg-white px-4 py-2">Care scope first</span><span className="rounded-full border border-slate-200 bg-white px-4 py-2">Final price confirmed by team</span><span className="rounded-full border border-slate-200 bg-white px-4 py-2">No automatic charge</span></div></div><div className="rounded-2xl border border-purple-100 bg-purple-50 p-6 sm:p-8"><CreditCard className="h-8 w-8 text-[#7C3AED]" /><h3 className="mt-4 text-xl font-bold text-slate-950">Enquiry-first services</h3><p className="mt-3 text-sm leading-7 text-slate-600">Talk to the care team before making any payment. This protects the family from paying against an unsuitable or unavailable arrangement.</p><Button asChild className="mt-6 h-12 w-full rounded-full bg-[#7C3AED] text-white hover:bg-[#6D28D9]"><a href={buildWhatsAppUrl(generalMessage)} target="_blank" rel="noreferrer"><MessageCircle className="mr-2 h-4 w-4" />Talk to Care Team First</a></Button></div></div></section>

    <section className="px-4 pb-12 sm:px-6 lg:px-8 lg:pb-20"><div className="mx-auto max-w-7xl rounded-2xl bg-[#312E81] px-6 py-10 text-white sm:px-10 lg:flex lg:items-center lg:justify-between lg:gap-10 lg:px-12"><div className="max-w-3xl"><CircleCheckBig className="h-8 w-8 text-purple-200" /><h2 className="mt-4 text-3xl font-bold sm:text-4xl">Whatever Your Family Needs, Start With a Conversation.</h2><p className="mt-4 leading-8 text-purple-100">Tell us what is happening. You don't need to know exactly which service or plan you need. Our team will help you understand the suitable option.</p></div><div className="mt-8 grid shrink-0 gap-3 sm:grid-cols-3 lg:mt-0 lg:grid-cols-1"><Button asChild className="h-12 rounded-full bg-white text-[#312E81] hover:bg-purple-50"><a href={buildWhatsAppUrl(generalMessage)} target="_blank" rel="noreferrer"><MessageCircle className="mr-2 h-4 w-4" />Connect on WhatsApp</a></Button><Button asChild variant="outline" className="h-12 rounded-full border-white/40 bg-transparent text-white hover:bg-white/10"><a href={siteContact.phoneHref}><Phone className="mr-2 h-4 w-4" />Call InstantCare</a></Button><Button asChild variant="outline" className="h-12 rounded-full border-white/40 bg-transparent text-white hover:bg-white/10"><a href="#connect-with-instantcare"><ClipboardCheck className="mr-2 h-4 w-4" />Request a Care Plan</a></Button></div></div></section>
  </>;
};

export default PricingStorySections;
