export const RESOURCE_DEFINITIONS = [
  {
    key: 'patients',
    routePath: 'patients',
    tableName: 'patients',
    entityName: 'patient',
    searchFields: ['full_name', 'email', 'phone'],
    readRoles: ['admin', 'coordinator', 'doctor', 'nurse'],
    writeRoles: ['admin', 'coordinator'],
  },
  {
    key: 'enquiries',
    routePath: 'enquiries',
    tableName: 'enquiries',
    entityName: 'enquiry',
    searchFields: ['full_name', 'email', 'service_required'],
    readRoles: ['admin', 'coordinator'],
    writeRoles: ['admin', 'coordinator'],
  },
  {
    key: 'services',
    routePath: 'services',
    tableName: 'services',
    entityName: 'service',
    searchFields: ['name', 'slug', 'category'],
    publicRead: true,
    writeRoles: ['admin', 'coordinator'],
  },
  {
    key: 'doctors',
    routePath: 'doctors',
    tableName: 'doctors',
    entityName: 'doctor',
    searchFields: ['full_name', 'speciality', 'city'],
    readRoles: ['admin', 'coordinator', 'doctor', 'nurse'],
    writeRoles: ['admin', 'coordinator'],
  },
  {
    key: 'nurses',
    routePath: 'nurses',
    tableName: 'nurses',
    entityName: 'nurse',
    searchFields: ['full_name', 'qualification', 'specialization'],
    readRoles: ['admin', 'coordinator', 'doctor', 'nurse'],
    writeRoles: ['admin', 'coordinator'],
  },
  {
    key: 'hospitals',
    routePath: 'hospitals',
    tableName: 'hospitals',
    entityName: 'hospital',
    searchFields: ['name', 'city', 'accreditation'],
    readRoles: ['admin', 'coordinator', 'doctor', 'nurse'],
    writeRoles: ['admin', 'coordinator'],
  },
  {
    key: 'appointments',
    routePath: 'appointments',
    tableName: 'appointments',
    entityName: 'appointment',
    searchFields: ['appointment_type', 'visit_type', 'status'],
    readRoles: ['admin', 'coordinator', 'doctor', 'nurse'],
    writeRoles: ['admin', 'coordinator'],
  },
  {
    key: 'staff',
    routePath: 'staff',
    tableName: 'staff',
    entityName: 'staff member',
    searchFields: ['full_name', 'role_title', 'city'],
    readRoles: ['admin', 'coordinator'],
    writeRoles: ['admin'],
  },
  {
    key: 'insurance',
    routePath: 'insurance',
    tableName: 'insurance',
    entityName: 'insurance case',
    searchFields: ['policy_number', 'provider_name', 'claim_id'],
    readRoles: ['admin', 'coordinator'],
    writeRoles: ['admin', 'coordinator'],
  },
  {
    key: 'billing',
    routePath: 'billing',
    tableName: 'invoices',
    entityName: 'invoice',
    searchFields: ['invoice_number', 'status', 'currency_code'],
    readRoles: ['admin', 'coordinator'],
    writeRoles: ['admin', 'coordinator'],
  },
  {
    key: 'reports',
    routePath: 'reports',
    tableName: 'medical_reports',
    entityName: 'medical report',
    searchFields: ['report_type', 'report_title', 'file_name'],
    readRoles: ['admin', 'coordinator', 'doctor', 'nurse'],
    writeRoles: ['admin', 'coordinator', 'doctor', 'nurse'],
  },
  {
    key: 'notifications',
    routePath: 'notifications',
    tableName: 'notifications',
    entityName: 'notification',
    searchFields: ['channel', 'subject', 'status'],
    readRoles: ['admin', 'coordinator'],
    writeRoles: ['admin', 'coordinator'],
  },
  {
    key: 'healthLibrary',
    routePath: 'health-library',
    tableName: 'articles',
    entityName: 'article',
    searchFields: ['title', 'slug', 'excerpt'],
    publicRead: true,
    writeRoles: ['admin', 'coordinator'],
  },
];

export const resourceKeys = RESOURCE_DEFINITIONS.map((item) => item.key);